---
name: Cache Cleanup

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup-caches:
    uses: miikkak/workflows/.github/workflows/cache-cleanup.yml@ef771e9b4fea176e07cb35a9e35096dcb7db5e10 # main
    secrets: inherit
