---
name: PR Validation

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ci-cd:
    uses: miikkak/workflows/.github/workflows/ci-cd.yml@3c052e17e880865f594222663c716ba3a9989667 # main
    with:
      runner: '["self-hosted","linux","x64"]'
      test-runner: '["self-hosted","linux","x64"]'
      code-paths: >-
        '**/*.go', 'go.mod', 'go.sum', '.github/workflows/**',
        '.pre-commit-config.yaml', '.releaserc.json'
      language-setup: go
