---
name: PR Check

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  pre-commit:
    uses: miikkak/workflows/.github/workflows/pr-check.yml@ef771e9b4fea176e07cb35a9e35096dcb7db5e10 # main
    secrets: inherit
