---
name: Pre-commit Hook Updates

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 9 * * 1"
  workflow_dispatch:


permissions:
  contents: write
  issues: write
  pull-requests: write

  actions: write
jobs:
  check-updates:
    uses: miikkak/workflows/.github/workflows/precommit-updates.yml@43ce0c3b01a799abd154c00c009dc7b2d8160d3c # main
    secrets: inherit
