---
name: Scheduled Security Scan

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  security:
    uses: miikkak/workflows/.github/workflows/security-scan.yml@550373595d009487da0c9dcc029b0ebd5507969f # main
    secrets: inherit
