---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@43ce0c3b01a799abd154c00c009dc7b2d8160d3c # main
    secrets: inherit
