---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@ef771e9b4fea176e07cb35a9e35096dcb7db5e10 # main
    secrets: inherit
